// <auto-generated/>
using System.Reflection;
using System.Windows;

[assembly: AssemblyTitleAttribute("WPFTagControl")]
[assembly: AssemblyProductAttribute("WPFTagControl")]
[assembly: AssemblyDescriptionAttribute("WPF control for tags/tokens")]
[assembly: AssemblyVersion("1.0.2")]
[assembly: AssemblyFileVersion("1.0.2")]
[assembly: ThemeInfoAttribute(ResourceDictionaryLocation.SourceAssembly, ResourceDictionaryLocation.SourceAssembly)]